<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-30 at 14:52:11.
 */
class FormInputsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var FormInputs
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers FormInputs::getVisible
     * @todo   Implement testGetVisible().
     */
    public function testGetVisible() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormInputs::getHidden
     * @todo   Implement testGetHidden().
     */
    public function testGetHidden() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormInputs::addVisible
     * @todo   Implement testAddVisible().
     */
    public function testAddVisible() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormInputs::addHidden
     * @todo   Implement testAddHidden().
     */
    public function testAddHidden() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
