<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-30 at 14:52:12.
 */
class ReportNotesTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ReportNotes
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers ReportNotes::init
     * @todo   Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportNotes::addPublisher
     * @todo   Implement testAddPublisher().
     */
    public function testAddPublisher() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportNotes::addPlatform
     * @todo   Implement testAddPlatform().
     */
    public function testAddPlatform() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportNotes::hasPublishers
     * @todo   Implement testHasPublishers().
     */
    public function testHasPublishers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportNotes::hasPlatforms
     * @todo   Implement testHasPlatforms().
     */
    public function testHasPlatforms() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportNotes::platformNotes
     * @todo   Implement testPlatformNotes().
     */
    public function testPlatformNotes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportNotes::publisherNotes
     * @todo   Implement testPublisherNotes().
     */
    public function testPublisherNotes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportNotes::displayNotes
     * @todo   Implement testDisplayNotes().
     */
    public function testDisplayNotes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
