<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-30 at 14:52:12.
 */
class ReportTableTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ReportTable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers ReportTable::displayHeader
     * @todo   Implement testDisplayHeader().
     */
    public function testDisplayHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportTable::prepareBody
     * @todo   Implement testPrepareBody().
     */
    public function testPrepareBody() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportTable::displayFooter
     * @todo   Implement testDisplayFooter().
     */
    public function testDisplayFooter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportTable::fields
     * @todo   Implement testFields().
     */
    public function testFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportTable::nfields
     * @todo   Implement testNfields().
     */
    public function testNfields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportTable::filterRow
     * @todo   Implement testFilterRow().
     */
    public function testFilterRow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportTable::formatColumn
     * @todo   Implement testFormatColumn().
     */
    public function testFormatColumn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportTable::formatTotalsRow
     * @todo   Implement testFormatTotalsRow().
     */
    public function testFormatTotalsRow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportTable::sumColumn
     * @todo   Implement testSumColumn().
     */
    public function testSumColumn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
