<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-30 at 15:39:12.
 */
class UsageStatisticsTopResourceRequestsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UsageStatisticsTopResourceRequests
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers UsageStatisticsTopResourceRequests::sql
     * @todo   Implement testSql().
     */
    public function testSql() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
