<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-30 at 14:52:14.
 */
class DBResultTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DBResult
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers DBResult::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBResult::hasData
     * @todo   Implement testHasData().
     */
    public function testHasData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBResult::numRows
     * @todo   Implement testNumRows().
     */
    public function testNumRows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBResult::fetchRow
     * @todo   Implement testFetchRow().
     */
    public function testFetchRow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBResult::fetchRowPersist
     * @todo   Implement testFetchRowPersist().
     */
    public function testFetchRowPersist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBResult::fetchRows
     * @todo   Implement testFetchRows().
     */
    public function testFetchRows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBResult::fetchFields
     * @todo   Implement testFetchFields().
     */
    public function testFetchFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
