ALTER DATABASE `_DATABASE_NAME_` CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `_DATABASE_NAME_`.`Report` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `_DATABASE_NAME_`.`ReportGroupingColumn` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `_DATABASE_NAME_`.`ReportParameter` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `_DATABASE_NAME_`.`ReportSum` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;