<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-30 at 15:39:15.
 */
class MultiselectParameterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MultiselectParameter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers MultiselectParameter::value
     * @todo   Implement testValue().
     */
    public function testValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MultiselectParameter::form
     * @todo   Implement testForm().
     */
    public function testForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MultiselectParameter::ajaxGetChildUpdate
     * @todo   Implement testAjaxGetChildUpdate().
     */
    public function testAjaxGetChildUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
