<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-30 at 15:12:44.
 */
class ParameterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Parameter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Parameter::value
     * @todo   Implement testValue().
     */
    public function testValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Parameter::process
     * @todo   Implement testProcess().
     */
    public function testProcess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Parameter::description
     * @todo   Implement testDescription().
     */
    public function testDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Parameter::form
     * @todo   Implement testForm().
     */
    public function testForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Parameter::ajaxGetChildUpdate
     * @todo   Implement testAjaxGetChildUpdate().
     */
    public function testAjaxGetChildUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Parameter::ajaxGetChildParameters
     * @todo   Implement testAjaxGetChildParameters().
     */
    public function testAjaxGetChildParameters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Parameter::setReport
     * @todo   Implement testSetReport().
     */
    public function testSetReport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Parameter::getSelectValues
     * @todo   Implement testGetSelectValues().
     */
    public function testGetSelectValues() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Parameter::isParent
     * @todo   Implement testIsParent().
     */
    public function testIsParent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Parameter::getChildren
     * @todo   Implement testGetChildren().
     */
    public function testGetChildren() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Parameter::getPubPlatDisplayName
     * @todo   Implement testGetPubPlatDisplayName().
     */
    public function testGetPubPlatDisplayName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
