<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-30 at 15:39:16.
 */
class ProviderPublisherParameterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ProviderPublisherParameter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers ProviderPublisherParameter::description
     * @todo   Implement testDescription().
     */
    public function testDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
